lenguage: java
jdk: oraclejdk8 

script: mvn clean package

deploy:
  provider: releases
  api_key: "8a793fc0fec89b26b4c9f40485a8f12814e1e833"
  file: "laboratorium-1.0.0-SNAPSHOT-shaded.jar"
  skip_cleanup: true
  draft: true